/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2024-03-08 08:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function fncLogin() {\r\n");
      out.write("		var id=document.loginForm.userId.value;\r\n");
      out.write("		var pw=document.loginForm.password.value;\r\n");
      out.write("		if(id == null || id.length <1) {\r\n");
      out.write("			alert('ID 를 입력하지 않으셨습니다.');\r\n");
      out.write("			document.loginForm.userId.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(pw == null || pw.length <1) {\r\n");
      out.write("			alert('패스워드를 입력하지 않으셨습니다.');\r\n");
      out.write("			document.loginForm.password.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	    document.loginForm.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\" >\r\n");
      out.write("\r\n");
      out.write("<form name=\"loginForm\"  method=\"post\" action=\"/login.do\" target=\"_parent\">\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<TABLE WITH=\"100%\" HEIGHT=\"100%\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\">\r\n");
      out.write("<TR>\r\n");
      out.write("<TD ALIGN=\"CENTER\" VALIGN=\"MIDDLE\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"650\" height=\"390\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#D6CDB7\">\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td width=\"10\" height=\"5\" align=\"left\" valign=\"top\" bordercolor=\"#D6CDB7\">\r\n");
      out.write("    	<table width=\"650\" height=\"390\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"305\">\r\n");
      out.write("            <img src=\"/images/logo-spring.png\" width=\"305\" height=\"390\">\r\n");
      out.write("          </td>\r\n");
      out.write("          <td width=\"345\" align=\"left\" valign=\"top\" background=\"/images/login02.gif\">\r\n");
      out.write("          	<table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td height=\"100\">&nbsp;</td>\r\n");
      out.write("                <td width=\"20\" height=\"100\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"50\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"50\">\r\n");
      out.write("                	<img src=\"/images/text_login.gif\" width=\"91\" height=\"32\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"50\">&nbsp;</td>\r\n");
      out.write("                <td width=\"20\" height=\"50\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"200\" height=\"50\" colspan=\"4\">\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>              \r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"30\">\r\n");
      out.write("                	<img src=\"/images/text_id.gif\" width=\"100\" height=\"30\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"30\">\r\n");
      out.write("                  <input 	type=\"text\" name=\"userId\"  class=\"ct_input_g\" \r\n");
      out.write("                  				style=\"width:180px; height:19px\"  maxLength='50'/>          \r\n");
      out.write("          		</td>\r\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"30\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"30\">\r\n");
      out.write("                	<img src=\"/images/text_pas.gif\" width=\"100\" height=\"30\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td height=\"30\">                    \r\n");
      out.write("                    <input 	type=\"password\" name=\"password\" class=\"ct_input_g\" \r\n");
      out.write("                    				style=\"width:180px; height:19px\"  maxLength=\"50\" >\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=\"20\" height=\"30\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr> \r\n");
      out.write("                <td width=\"30\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                <td width=\"100\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                <td height=\"20\" align=\"center\">\r\n");
      out.write("      				<table width=\"136\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                          <tr> \r\n");
      out.write("                            <td width=\"56\">\r\n");
      out.write("                            	<a href=\"javascript:fncLogin();\">\r\n");
      out.write("                            		<img src=\"/images/btn_login.gif\" width=\"56\" height=\"20\" border=\"0\">\r\n");
      out.write("                            	</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td width=\"10\">&nbsp;</td>\r\n");
      out.write("                            <td width=\"70\">\r\n");
      out.write("                            	<a href=\"addUserView.jsp;\">\r\n");
      out.write("                            		<img src=\"/images/btn_add.gif\" width=\"70\" height=\"20\" border=\"0\">\r\n");
      out.write("                            	</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td width=\"20\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>                            \r\n");
      out.write("      </table>\r\n");
      out.write("      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	document.loginForm.userId.focus();\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
