/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2024-03-08 08:10:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model2.mvc.service.purchase.vo.*;

public final class getPurchase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.model2.mvc.service.purchase.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	PurchaseVO pur = (PurchaseVO)request.getAttribute("pur");
	System.out.println(pur);
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>구매상세조회</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"15\" height=\"37\">\r\n");
      out.write("			<img src=\"/images/ct_ttl_img01.gif\"	width=\"15\" height=\"37\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left: 10px;\">\r\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"93%\" class=\"ct_ttl01\">구매상세조회</td>\r\n");
      out.write("					<td width=\"20%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"12\" height=\"37\">\r\n");
      out.write("			<img src=\"/images/ct_ttl_img03.gif\"	width=\"12\" height=\"37\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"	style=\"margin-top: 13px;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			물품번호 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"105\">\r\n");
      out.write("					");
      out.print( pur.getPurchaseProd().getProdNo() );
      out.write("</td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			구매자아이디 <img	src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print( pur.getBuyer().getUserId() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">구매방법</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			");
 if ( pur.getPaymentOption().equals("1")) { 
      out.write("\r\n");
      out.write("				현금구매\r\n");
      out.write("			");
}else if( pur.getPaymentOption().equals("2")){
      out.write("\r\n");
      out.write("				신용구매\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">구매자이름</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print(pur.getReceiverName() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">구매자연락처</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print(pur.getReceiverPhone() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">구매자주소</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print(pur.getDivyAddr() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">구매요청사항</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print(pur.getDivyRequest() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">배송희망일</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print(pur.getDivyDate() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">주문일</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">");
      out.print( pur.getOrderDate() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"	style=\"margin-top: 10px;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"53%\"></td>\r\n");
      out.write("		<td align=\"right\">\r\n");
      out.write("			<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"17\" height=\"23\">\r\n");
      out.write("						<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\"	style=\"padding-top: 3px;\">\r\n");
      out.write("						<a href=\"/updatePurchaseView.do?tranNo=");
      out.print( pur.getTranNo() );
      out.write("\">수정</a>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"14\" height=\"23\">\r\n");
      out.write("						<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"30\"></td>\r\n");
      out.write("					<td width=\"17\" height=\"23\">\r\n");
      out.write("						<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\"	style=\"padding-top: 3px;\">\r\n");
      out.write("						<a href=\"javascript:history.go(-1);\">확인</a>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td width=\"14\" height=\"23\">\r\n");
      out.write("						<img src=\"/images/ct_btnbg03.gif\"width=\"14\" height=\"23\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
